version: '3.8'

services:
  # Neon Local Proxy - creates ephemeral branches for development
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    networks:
      - acquisitions-network
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '5432']
      interval: 10s
      timeout: 5s
      retries: 5

  # Application container
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for development hot reload
      - .:/app
      - /app/node_modules
      # Mount logs directory
      - ./logs:/app/logs
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-network
    command: ['npm', 'run', 'dev']

networks:
  acquisitions-network:
    driver: bridge
