version: '3.8'

services:
  # Application container for production
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: acquisitions-app-prod
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    volumes:
      # Mount logs directory only (no source code mounting in production)
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - acquisitions-network
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a reverse proxy for production (nginx)
  nginx:
    image: nginx:alpine
    container_name: acquisitions-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates if needed
      # - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
    networks:
      - acquisitions-network
    restart: unless-stopped

networks:
  acquisitions-network:
    driver: bridge
