name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          if ! npm run lint; then
            echo "::error::ESLint found issues. Run 'npm run lint:fix' to automatically fix some issues."
            exit 1
          fi

      - name: Check Prettier formatting
        run: |
          if ! npm run format:check; then
            echo "::error::Code is not properly formatted. Run 'npm run format' to fix formatting issues."
            exit 1
          fi

      - name: Lint and format success
        if: success()
        run: |
          echo "✅ All linting and formatting checks passed!"
          echo "::notice::Code follows the project's linting and formatting standards."
